### ISSUE TITLE
Support for cmasher colormaps?

### ISSUE THREAD

**Issue by TomLav** [TomLav/ncmaps#1]
Should cmaps also bring scientific colormaps from cmasher

(CMasher: Scientific colormaps for making accessible, informative and cmashing plots) ?
https://pypi.org/project/cmasher/

Do you use these @samhatfield ?

**Comment by samhatfield** [comment]
I've never used cmasher, but it wouldn't hurt to have more options!

**Comment by TomLav** [comment]
I will see if this is straightforward.
