### ISSUE TITLE
Screenshots of the colourmaps

### ISSUE THREAD

**Issue by magnusuMET** [TomLav/ncmaps#2]
This looks quite interesting and would make comparisons of my dispersion maps easier. Could you add a couple of examples of the colourmaps in use to the README?

**Comment by samhatfield** [comment]
Good idea. @TomLav - I have a nice high-resolution output file from an atmospheric model (IFS), which I used in the README.md of [ncview-scientific-colour-maps](https://github.com/samhatfield/ncview-scientific-colour-maps). I can't run ncview on my personal computer anymore so I won't be able to make a screenshot myself, but if you like I can send you the file so you can screenshot ncview with a few recommended colormaps selected? It's about 2GB unzipped.

**Comment by TomLav** [comment]
I indeed think we could show ncview screenshots for a subset (~4?) of the colormaps on the frontpage of the repo.

But I would not do a full listing of the colormaps we support, and rather link to the home page of the colormaps as we do today.

**Comment by samhatfield** [comment]
I agree. I've added 3 screenshots (see https://github.com/TomLav/ncmaps/tree/add_screenshots) - one from each colormap package. I'll add one from cmasher too once that's pulled.

**Comment by TomLav** [comment]
Excellent, thank you. Could you create a PR?
